### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by ST33LDI9ITAL** [UltiRequiem/chigo#3]
![SCR-20220425-qme-2](https://user-images.githubusercontent.com/12997114/165189580-54797543-b81e-4e1b-861e-228e07d1cde8.png)

**Comment by UltiRequiem** [comment]
Very weird, I just made a fresh go install, I just format my computer like a week ago, install chigo (from latest as in the readme), dadjokes ( I'm guessing you are using https://github.com/UltiRequiem/dadjokes), and cowsay (is not included by default on archlinux 😔) and is working (almost) correctly.

> We shouldn't include EOF, but it shouldn't be hard to fix 🧐 

![image](https://user-images.githubusercontent.com/71897736/165199194-33231234-6fc1-439f-8e42-351388017bf3.png)

Could you give me more info about your cli & system?

**Comment by UltiRequiem** [comment]
Closed due to inactivity and because I can't replicate it.
